-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 27/11/2025 13:30:32
-- Server version: 5.5.5-10.4.32-MariaDB
-- Client version: 4.1

-- ------
-- GRADOS
-- ------
SET NAMES 'utf8';
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(1, True, 'Matías Ruiz', 'PRIMERO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(2, True, 'Vanesa Leiva', 'SEGUNDO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(3, True, 'Julieta Pérez', 'TERCERO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(4, True, 'Adriana Arias', 'CUARTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(5, True, 'Pedro González', 'QUINTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(6, True, 'Daiana Giménez', 'SEXTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(7, True, 'Roxana Costa', 'SEPTIMO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(8, True, 'Juan Pérez', 'PRIMERO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(9, True, 'María Fernández', 'SEGUNDO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(10, True, 'Laura González', 'TERCERO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(11, True, 'Sofía Gómez', 'CUARTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(12, True, 'Esteban Sánchez', 'QUINTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(13, True, 'Ana Ruiz', 'SEXTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(14, True, 'Diego Díaz', 'SEPTIMO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(15, True, 'Andrés Benítez', 'PRIMERO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(16, True, 'Marcela Morales', 'SEGUNDO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(17, True, 'Sofía Mariana Gómez', 'TERCERO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(18, True, 'Alejandro López', 'CUARTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(19, True, 'Valeria Torres', 'QUINTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(20, True, 'Gabriela Acosta', 'SEXTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(21, True, 'Florencia Benítez', 'SEPTIMO', 'JORNADA_COMPLETA');


-- -----------
-- ESTUDIANTES
-- -----------
-- 1° grado TM
/* 1. Estudiante de 5 años (Femenino) */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('García', 'Av. San Martín 100', '48000001', 5, 0, 'Sofía', 'Ana García', 'Luis García', 1, 1);

/* 2. Estudiantes de 7 años (1 Femenino, 1 Masculino) */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rodríguez', 'Calle Belgrano 200', '48000002', 7, 1, 'Valentina', 'Marta Rodríguez', 'Jorge Rodríguez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('González', 'Calle Mitre 300', '48000003', 7, 0, 'Mateo', 'Lucía González', 'Pedro González', 1, 1);

/* 3. Estudiantes de 6 años - Resto de Varones (9 registros restantes para completar los 10 varones totales) */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('López', 'Calle Sarmiento 400', '48000004', 6, 0, 'Santiago', 'Elena López', 'Miguel López', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Martínez', 'Calle Rivadavia 500', '48000005', 6, 1, 'Benjamín', 'Sofía Martínez', 'Carlos Martínez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Pérez', 'Calle Alvear 600', '48000006', 6, 0, 'Lucas', 'Laura Pérez', 'Diego Pérez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Álvarez', 'Calle Moreno 700', '48000007', 6, 0, 'Thiago', 'María Álvarez', 'Javier Álvarez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Romero', 'Calle Urquiza 800', '48000008', 6, 1, 'Joaquín', 'Paula Romero', 'Fernando Romero', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Sosa', 'Calle 9 de Julio 900', '48000009', 6, 0, 'Lautaro', 'Clara Sosa', 'Roberto Sosa', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ruiz', 'Calle Colon 1000', '48000010', 6, 0, 'Gabriel', 'Patricia Ruiz', 'Ricardo Ruiz', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Torres', 'Calle Paz 1100', '48000011', 6, 1, 'Bautista', 'Carmen Torres', 'Hugo Torres', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Flores', 'Calle Libertad 1200', '48000012', 6, 0, 'Felipe', 'Teresa Flores', 'Manuel Flores', 1, 1);

/* 4. Estudiantes de 6 años - Resto de Mujeres (14 registros restantes para completar las 16 mujeres totales) */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Benítez', 'Calle Roca 1300', '48000013', 6, 0, 'Isabella', 'Adriana Benítez', 'Oscar Benítez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ramírez', 'Calle Salta 1400', '48000014', 6, 1, 'Camila', 'Silvia Ramírez', 'Andrés Ramírez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Herrera', 'Calle Jujuy 1500', '48000015', 6, 0, 'Mía', 'Natalia Herrera', 'Guillermo Herrera', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Acosta', 'Calle Tucumán 1600', '48000016', 6, 0, 'Julieta', 'Mónica Acosta', 'Gustavo Acosta', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Medina', 'Calle Córdoba 1700', '48000017', 6, 1, 'Emma', 'Alicia Medina', 'Sergio Medina', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rojas', 'Calle Mendoza 1800', '48000018', 6, 0, 'Martina', 'Daniela Rojas', 'Alberto Rojas', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Molina', 'Calle San Juan 1900', '48000019', 6, 0, 'Lucía', 'Lorena Molina', 'Eduardo Molina', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Castro', 'Calle Entre Ríos 2000', '48000020', 6, 1, 'Catalina', 'Gabriela Castro', 'Mariano Castro', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ortiz', 'Calle Santa Fe 2100', '48000021', 6, 0, 'Victoria', 'Verónica Ortiz', 'Pablo Ortiz', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Silva', 'Calle Misiones 2200', '48000022', 6, 0, 'Elena', 'Beatriz Silva', 'Fabián Silva', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Núñez', 'Calle Chaco 2300', '48000023', 6, 1, 'Emilia', 'Cecilia Núñez', 'Esteban Núñez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Luna', 'Calle La Pampa 2400', '48000024', 6, 0, 'Zoe', 'Inés Luna', 'Lucas Luna', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Juárez', 'Calle Río Negro 2500', '48000025', 6, 0, 'Alma', 'Carolina Juárez', 'Martín Juárez', 1, 1);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Cabrera', 'Calle Neuquén 2600', '48000026', 6, 1, 'Renata', 'Flavia Cabrera', 'Sebastián Cabrera', 1, 1);

-- 2° grado TM
/* 1. Varones (8 registros) - EDAD: 6 y 7 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Díaz', 'Calle Falsa 111', '49000001', 7, 0, 'Diego', 'Alejandra Díaz', 'Julio Díaz', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Gómez', 'Avenida Real 222', '49000002', 6, 1, 'Marco', 'Andrea Gómez', 'Héctor Gómez', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Muñoz', 'Pasaje Central 333', '49000003', 7, 0, 'Pedro', 'Yanina Muñoz', 'Ramiro Muñoz', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vargas', 'Ruta 5 Km 10', '49000004', 6, 0, 'Ian', 'Carolina Vargas', 'Marcelo Vargas', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Méndez', 'Barrio Norte 444', '49000005', 7, 1, 'Leo', 'Erica Méndez', 'Juan Méndez', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Peralta', 'Calle 100 Nro 555', '49000006', 6, 0, 'Alex', 'Romina Peralta', 'Sergio Peralta', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rivas', 'Callejon Oscuro 666', '49000007', 7, 0, 'Santino', 'Jesica Rivas', 'Matías Rivas', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Sánchez', 'Av. del Bosque 777', '49000008', 6, 1, 'Máximo', 'Florencia Sánchez', 'Germán Sánchez', 1, 2);

/* 2. Mujeres (11 registros) - EDAD: 6 y 7 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Quinteros', 'Calle Larga 888', '49000009', 6, 0, 'Abril', 'Cecilia Quinteros', 'Rubén Quinteros', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ramos', 'Pasaje Chico 999', '49000010', 7, 1, 'Olivia', 'Diana Ramos', 'Pablo Ramos', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vega', 'Calle Principal 1010', '49000011', 6, 0, 'Jazmín', 'Estela Vega', 'Hugo Vega', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Zarate', 'Av. Del Sol 1111', '49000012', 7, 0, 'Pilar', 'Mabel Zarate', 'Néstor Zarate', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Herrera', 'Calle Las Flores 1212', '49000013', 6, 1, 'Nicole', 'Susana Herrera', 'Leo Herrera', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ibarra', 'Ruta 9 Km 20', '49000014', 7, 0, 'Alma', 'Valeria Ibarra', 'Cristian Ibarra', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ríos', 'Callejón Sur 1313', '49000015', 6, 0, 'Amelia', 'Viviana Ríos', 'Enrique Ríos', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Franco', 'Av. Costanera 1414', '49000016', 7, 1, 'Delfina', 'Ximena Franco', 'Darío Franco', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Gallo', 'Calle 50 Nro 1515', '49000017', 6, 0, 'Bianca', 'Yolanda Gallo', 'Raúl Gallo', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Navarro', 'Pasaje Río 1616', '49000018', 7, 0, 'Gina', 'Zulma Navarro', 'José Navarro', 1, 2);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Palma', 'Barrio Oeste 1717', '49000019', 6, 1, 'Emma', 'Blanca Palma', 'César Palma', 1, 2);

-- -----------
-- 3° grado TM
-- -----------
/* 1. Varones (8 registros) - EDAD: 7 y 8 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Blanco', 'Av. De Mayo 10', '50000001', 8, 1, 'Nicolás', 'Susana Blanco', 'Alfredo Blanco', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Costa', 'Calle Junín 20', '50000002', 7, 0, 'Tomás', 'Sandra Costa', 'Ramón Costa', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Giménez', 'Barrio Obrero 30', '50000003', 8, 0, 'Facundo', 'Brenda Giménez', 'Hugo Giménez', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Iriarte', 'Pasaje La Paz 40', '50000004', 7, 1, 'Juan', 'Eliana Iriarte', 'Mauro Iriarte', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Montes', 'Ruta Vieja 50', '50000005', 8, 0, 'Franco', 'Mónica Montes', 'Saúl Montes', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Nieto', 'Calle de las Rosas 60', '50000006', 7, 0, 'Simón', 'Nora Nieto', 'Omar Nieto', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Paz', 'Av. Circunvalación 70', '50000007', 8, 1, 'Ignacio', 'Ruth Paz', 'Vicente Paz', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vera', 'Calle Pringles 80', '50000008', 7, 0, 'Ezequiel', 'Tatiana Vera', 'Ulises Vera', 1, 3);

/* 2. Mujeres (13 registros) - EDAD: 7 y 8 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Aguirre', 'Pasaje Sol 90', '50000009', 7, 0, 'Abigail', 'Zoe Aguirre', 'Ariel Aguirre', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Cano', 'Calle del Río 100', '50000010', 8, 1, 'Guadalupe', 'Brenda Cano', 'Carlos Cano', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Duarte', 'Av. Del Este 110', '50000011', 7, 0, 'Agustina', 'Cinthia Duarte', 'Damián Duarte', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Figueroa', 'Callejón Sur 120', '50000012', 8, 0, 'Aldana', 'Emilia Figueroa', 'Fabián Figueroa', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Juárez', 'Calle 10 Nro 130', '50000013', 7, 1, 'Candela', 'Gisela Juárez', 'Horacio Juárez', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Leiva', 'Av. Central 140', '50000014', 8, 0, 'Daina', 'Ivana Leiva', 'Julián Leiva', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Méndez', 'Pasaje Chico 150', '50000015', 7, 0, 'Estefanía', 'Karina Méndez', 'Lucas Méndez', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Núñez', 'Ruta Provincial 160', '50000016', 8, 1, 'Felicitas', 'Luciana Núñez', 'Martín Núñez', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Quiroga', 'Barrio Unido 170', '50000017', 7, 0, 'Malena', 'Natalia Quiroga', 'Octavio Quiroga', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ramos', 'Calle Sarmiento 180', '50000018', 8, 0, 'Sofía', 'Paola Ramos', 'Ricardo Ramos', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Salas', 'Av. Roca 190', '50000019', 7, 1, 'Tamara', 'Sandra Salas', 'Tobías Salas', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Toledo', 'Pasaje Central 200', '50000020', 8, 0, 'Victoria', 'Úrsula Toledo', 'Víctor Toledo', 1, 3);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Zarate', 'Calle Belgrano 210', '50000021', 7, 0, 'Ximena', 'Wendy Zarate', 'Yago Zarate', 1, 3);


-- -----------
-- 4° grado TM
-- -----------
/* 1. Varones (7 registros) - EDAD: 8 y 9 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Gutiérrez', 'Calle La Rioja 300', '51000001', 9, 0, 'Benicio', 'Laura Gutiérrez', 'Carlos Gutiérrez', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Hernández', 'Av. Corrientes 400', '51000002', 8, 1, 'Ciro', 'Mónica Hernández', 'Daniel Hernández', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vega', 'Pasaje Paraná 500', '51000003', 9, 0, 'Dante', 'Natalia Vega', 'Ernesto Vega', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ponce', 'Ruta 11 Km 15', '51000004', 8, 0, 'Elián', 'Sofía Ponce', 'Felipe Ponce', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Coronel', 'Calle Entre Ríos 600', '51000005', 9, 1, 'Genaro', 'Úrsula Coronel', 'Gabriel Coronel', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ferreyra', 'Av. 25 de Mayo 700', '51000006', 8, 0, 'Israel', 'Valeria Ferreyra', 'Horacio Ferreyra', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Nieva', 'Pasaje Tucumán 800', '51000007', 9, 0, 'Lisandro', 'Ximena Nieva', 'Iker Nieva', 1, 4);

/* 2. Mujeres (10 registros) - EDAD: 8 y 9 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Silva', 'Calle Junín 900', '51000008', 8, 0, 'Alma', 'Yésica Silva', 'Javier Silva', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Gallo', 'Av. Córdoba 1000', '51000009', 9, 1, 'Alma', 'Zaira Gallo', 'Kevin Gallo', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Peralta', 'Pasaje Misiones 1100', '51000010', 8, 0, 'Paula', 'Andrea Peralta', 'Leo Peralta', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rojas', 'Ruta Nacional 12', '51000011', 9, 0, 'Jazmín', 'Bárbara Rojas', 'Max Rojas', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vázquez', 'Calle Catamarca 1300', '51000012', 8, 1, 'Sofía', 'Carla Vázquez', 'Nico Vázquez', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Chaves', 'Av. Entre Ríos 1400', '51000013', 9, 0, 'Milagros', 'Daniela Chaves', 'Osvaldo Chaves', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Duarte', 'Pasaje Chaco 1500', '51000014', 8, 0, 'Renata', 'Érica Duarte', 'Pedro Duarte', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Olmos', 'Calle Formosa 1600', '51000015', 9, 1, 'Abril', 'Florencia Olmos', 'Quique Olmos', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Riquelme', 'Av. Mendoza 1700', '51000016', 8, 0, 'Emilia', 'Gisela Riquelme', 'Ramiro Riquelme', 1, 4);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Sosa', 'Calle Santiago 1800', '51000017', 9, 0, 'Violeta', 'Hilda Sosa', 'Sebastián Sosa', 1, 4);

-- -----------
-- 5° grado TM
-- -----------
/* 1. Varones (6 registros) - EDAD: 9 y 10 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('García', 'Calle de los Álamos 10', '52000001', 10, 0, 'Julián', 'María García', 'Roberto García', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rodríguez', 'Av. Las Palmas 20', '52000002', 9, 1, 'Mateo', 'Ana Rodríguez', 'Felipe Rodríguez', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Pérez', 'Ruta 3 Km 5', '52000003', 10, 0, 'Oliver', 'Elena Pérez', 'Pablo Pérez', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('López', 'Pasaje del Oeste 30', '52000004', 9, 0, 'Ramiro', 'Juana López', 'Sebastián López', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Sosa', 'Calle Mitre 40', '52000005', 10, 1, 'Ulises', 'Carla Sosa', 'Víctor Sosa', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Gómez', 'Av. España 50', '52000006', 9, 0, 'Valentino', 'Diana Gómez', 'Walter Gómez', 1, 5);

/* 2. Mujeres (10 registros) - EDAD: 9 y 10 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Acosta', 'Calle San Luis 60', '52000007', 9, 0, 'Luciana', 'Florencia Acosta', 'Héctor Acosta', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Díaz', 'Pasaje La Pampa 70', '52000008', 10, 1, 'Morena', 'Gabriela Díaz', 'Iván Díaz', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ramos', 'Ruta 9 Km 25', '52000009', 9, 0, 'Naomi', 'Irma Ramos', 'Julián Ramos', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Torres', 'Calle Tucumán 80', '52000010', 10, 0, 'Zoe', 'Laura Torres', 'Marcos Torres', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vega', 'Av. San Juan 90', '52000011', 9, 1, 'Abril', 'Nadia Vega', 'Óscar Vega', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Luna', 'Pasaje Salta 100', '52000012', 10, 0, 'Mia', 'Patricia Luna', 'Renzo Luna', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Núñez', 'Calle Viamonte 110', '52000013', 9, 0, 'Erika', 'Silvina Núñez', 'Tadeo Núñez', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ríos', 'Av. Las Heras 120', '52000014', 10, 1, 'Martina', 'Úrsula Ríos', 'Víctor Ríos', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Franco', 'Calle Sarmiento 130', '52000015', 9, 0, 'Julieta', 'Ximena Franco', 'Yair Franco', 1, 5);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Benítez', 'Pasaje Misiones 140', '52000016', 10, 0, 'Valentina', 'Yésica Benítez', 'Zacarías Benítez', 1, 5);

-- -----------
-- 6° grado TM
-- -----------
/* 1. Varones (8 registros) - EDAD: 10 y 11 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Quiroga', 'Av. del Puerto 150', '53000001', 11, 0, 'Lucas', 'Mariana Quiroga', 'Daniel Quiroga', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Rojas', 'Calle La Plata 160', '53000002', 10, 1, 'Mateo', 'Ana Rojas', 'Javier Rojas', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Silva', 'Pasaje del Sol 170', '53000003', 11, 0, 'Nicolás', 'Carolina Silva', 'Esteban Silva', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Torres', 'Ruta 7 Km 30', '53000004', 10, 0, 'Pablo', 'Florencia Torres', 'Guido Torres', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Vega', 'Calle Chacabuco 180', '53000005', 11, 1, 'Ricardo', 'Helena Vega', 'Iván Vega', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Méndez', 'Av. 9 de Julio 190', '53000006', 10, 0, 'Thiago', 'Inés Méndez', 'Kike Méndez', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ortiz', 'Pasaje Las Flores 200', '53000007', 11, 0, 'Valentino', 'Juana Ortiz', 'Leo Ortiz', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Paz', 'Calle Misiones 210', '53000008', 10, 1, 'Zacarías', 'Karina Paz', 'Manuel Paz', 1, 6);

/* 2. Mujeres (11 registros) - EDAD: 10 y 11 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Arias', 'Av. Libertador 220', '53000009', 10, 0, 'Victoria', 'Lorena Arias', 'Néstor Arias', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Benítez', 'Ruta 8 Km 40', '53000010', 11, 1, 'Zoe', 'Micaela Benítez', 'Octavio Benítez', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Castro', 'Calle Sarmiento 230', '53000011', 10, 0, 'Catalina', 'Noemí Castro', 'Pedro Castro', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Díaz', 'Pasaje Norte 240', '53000012', 11, 0, 'Delfina', 'Olga Díaz', 'Quique Díaz', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Franco', 'Av. San Martín 250', '53000013', 10, 1, 'Guillermina', 'Patricia Franco', 'Raúl Franco', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Giménez', 'Calle Las Heras 260', '53000014', 11, 0, 'Lucía', 'Rocío Giménez', 'Sergio Giménez', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ibarra', 'Pasaje Córdoba 270', '53000015', 10, 0, 'Martina', 'Silvia Ibarra', 'Tito Ibarra', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Juárez', 'Av. Roca 280', '53000016', 11, 1, 'Olivia', 'Teresa Juárez', 'Ulises Juárez', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('López', 'Calle Jujuy 290', '53000017', 10, 0, 'Paz', 'Úrsula López', 'Víctor López', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Morales', 'Ruta 6 Km 18', '53000018', 11, 0, 'Renata', 'Virginia Morales', 'Walter Morales', 1, 6);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Núñez', 'Av. Belgrano 300', '53000019', 10, 1, 'Sofía', 'Ximena Núñez', 'Yago Núñez', 1, 6);

-- -----------
-- 7° grado TM
-- -----------
/* 1. Varones (6 registros) - EDAD: 11 y 12 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Chávez', 'Calle Principal 15', '54000001', 12, 0, 'Alexander', 'Laura Chávez', 'Martín Chávez', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Escobar', 'Av. 12 de Octubre 25', '54000002', 11, 1, 'Brian', 'Noelia Escobar', 'Pablo Escobar', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Herrera', 'Pasaje del Centro 35', '54000003', 12, 0, 'Kevin', 'Silvia Herrera', 'Ricardo Herrera', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Juárez', 'Ruta 14 Km 50', '54000004', 11, 0, 'Marcelo', 'Tania Juárez', 'Ulises Juárez', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Pereyra', 'Calle Los Sauces 45', '54000005', 12, 1, 'Santiago', 'Viviana Pereyra', 'Walter Pereyra', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ramos', 'Av. Belgrano 55', '54000006', 11, 0, 'Sebastián', 'Ximena Ramos', 'Yago Ramos', 1, 7);

/* 2. Mujeres (8 registros) - EDAD: 11 y 12 años */
INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Acosta', 'Pasaje Sarmiento 65', '54000007', 12, 0, 'Abril', 'Andrea Acosta', 'Beto Acosta', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Díaz', 'Calle San Juan 75', '54000008', 11, 1, 'Brenda', 'Carla Díaz', 'Dario Díaz', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Giménez', 'Av. Rivadavia 85', '54000009', 12, 0, 'Camila', 'Elena Giménez', 'Fede Giménez', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('López', 'Ruta 38 Km 10', '54000010', 11, 0, 'Jazmín', 'Gloria López', 'Hugo López', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Martínez', 'Calle 25 de Mayo 95', '54000011', 12, 1, 'Laura', 'Inés Martínez', 'Juan Martínez', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Núñez', 'Pasaje La Rioja 105', '54000012', 11, 0, 'Sofía', 'Karina Núñez', 'Leo Núñez', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Ortiz', 'Av. San Martín 115', '54000013', 12, 0, 'Valentina', 'Marta Ortiz', 'Nico Ortiz', 1, 7);

INSERT INTO estudiantes (apellido, direccion, dni, edad, hno_en_escuela, nombre, nombre_madre, nombre_padre, regular, id_grado) 
VALUES ('Pérez', 'Calle Salta 125', '54000014', 11, 1, 'Zoe', 'Olivia Pérez', 'Pato Pérez', 1, 7);


-- -----------
-- ASISTENCIAS
-- -----------
INSERT INTO asistencias (fecha, tipo_asistencia, id_estudiante) VALUES 
/* ID ESTUDIANTE 119 */
('2025-03-03', 'PRESENTE', 119),
('2025-03-04', 'PRESENTE', 119),
('2025-03-05', 'PRESENTE', 119),
('2025-03-06', 'PRESENTE', 119),
('2025-03-07', 'TARDE', 119),
('2025-03-10', 'PRESENTE', 119),
('2025-03-11', 'AUSENTE', 119),
('2025-03-12', 'PRESENTE', 119),
('2025-03-13', 'TARDE', 119),
('2025-03-14', 'PRESENTE', 119),

/* ID ESTUDIANTE 120 */
('2025-03-03', 'PRESENTE', 120),
('2025-03-04', 'TARDE', 120),
('2025-03-05', 'PRESENTE', 120),
('2025-03-06', 'PRESENTE', 120),
('2025-03-07', 'PRESENTE', 120),
('2025-03-10', 'PRESENTE', 120),
('2025-03-11', 'PRESENTE', 120),
('2025-03-12', 'TARDE', 120),
('2025-03-13', 'AUSENTE', 120),
('2025-03-14', 'PRESENTE', 120),

/* ID ESTUDIANTE 121 */
('2025-03-03', 'PRESENTE', 121),
('2025-03-04', 'PRESENTE', 121),
('2025-03-05', 'AUSENTE', 121),
('2025-03-06', 'PRESENTE', 121),
('2025-03-07', 'TARDE', 121),
('2025-03-10', 'PRESENTE', 121),
('2025-03-11', 'PRESENTE', 121),
('2025-03-12', 'PRESENTE', 121),
('2025-03-13', 'PRESENTE', 121),
('2025-03-14', 'TARDE', 121),

/* ID ESTUDIANTE 122 */
('2025-03-03', 'TARDE', 122),
('2025-03-04', 'PRESENTE', 122),
('2025-03-05', 'PRESENTE', 122),
('2025-03-06', 'PRESENTE', 122),
('2025-03-07', 'AUSENTE', 122),
('2025-03-10', 'PRESENTE', 122),
('2025-03-11', 'PRESENTE', 122),
('2025-03-12', 'PRESENTE', 122),
('2025-03-13', 'TARDE', 122),
('2025-03-14', 'PRESENTE', 122),

/* ID ESTUDIANTE 123 */
('2025-03-03', 'PRESENTE', 123),
('2025-03-04', 'PRESENTE', 123),
('2025-03-05', 'PRESENTE', 123),
('2025-03-06', 'TARDE', 123),
('2025-03-07', 'PRESENTE', 123),
('2025-03-10', 'AUSENTE', 123),
('2025-03-11', 'PRESENTE', 123),
('2025-03-12', 'PRESENTE', 123),
('2025-03-13', 'PRESENTE', 123),
('2025-03-14', 'TARDE', 123),

/* ID ESTUDIANTE 124 */
('2025-03-03', 'PRESENTE', 124),
('2025-03-04', 'PRESENTE', 124),
('2025-03-05', 'TARDE', 124),
('2025-03-06', 'AUSENTE', 124),
('2025-03-07', 'PRESENTE', 124),
('2025-03-10', 'PRESENTE', 124),
('2025-03-11', 'PRESENTE', 124),
('2025-03-12', 'PRESENTE', 124),
('2025-03-13', 'TARDE', 124),
('2025-03-14', 'PRESENTE', 124),

/* ID ESTUDIANTE 125 */
('2025-03-03', 'TARDE', 125),
('2025-03-04', 'PRESENTE', 125),
('2025-03-05', 'PRESENTE', 125),
('2025-03-06', 'PRESENTE', 125),
('2025-03-07', 'PRESENTE', 125),
('2025-03-10', 'PRESENTE', 125),
('2025-03-11', 'TARDE', 125),
('2025-03-12', 'AUSENTE', 125),
('2025-03-13', 'PRESENTE', 125),
('2025-03-14', 'PRESENTE', 125),

/* ID ESTUDIANTE 126 */
('2025-03-03', 'PRESENTE', 126),
('2025-03-04', 'PRESENTE', 126),
('2025-03-05', 'TARDE', 126),
('2025-03-06', 'PRESENTE', 126),
('2025-03-07', 'PRESENTE', 126),
('2025-03-10', 'PRESENTE', 126),
('2025-03-11', 'PRESENTE', 126),
('2025-03-12', 'TARDE', 126),
('2025-03-13', 'PRESENTE', 126),
('2025-03-14', 'AUSENTE', 126),

/* ID ESTUDIANTE 127 */
('2025-03-03', 'PRESENTE', 127),
('2025-03-04', 'TARDE', 127),
('2025-03-05', 'PRESENTE', 127),
('2025-03-06', 'PRESENTE', 127),
('2025-03-07', 'PRESENTE', 127),
('2025-03-10', 'PRESENTE', 127),
('2025-03-11', 'PRESENTE', 127),
('2025-03-12', 'AUSENTE', 127),
('2025-03-13', 'PRESENTE', 127),
('2025-03-14', 'TARDE', 127),

/* ID ESTUDIANTE 128 */
('2025-03-03', 'TARDE', 128),
('2025-03-04', 'PRESENTE', 128),
('2025-03-05', 'PRESENTE', 128),
('2025-03-06', 'PRESENTE', 128),
('2025-03-07', 'PRESENTE', 128),
('2025-03-10', 'PRESENTE', 128),
('2025-03-11', 'AUSENTE', 128),
('2025-03-12', 'TARDE', 128),
('2025-03-13', 'PRESENTE', 128),
('2025-03-14', 'PRESENTE', 128),

/* ID ESTUDIANTE 129 */
('2025-03-03', 'PRESENTE', 129),
('2025-03-04', 'PRESENTE', 129),
('2025-03-05', 'PRESENTE', 129),
('2025-03-06', 'PRESENTE', 129),
('2025-03-07', 'TARDE', 129),
('2025-03-10', 'PRESENTE', 129),
('2025-03-11', 'PRESENTE', 129),
('2025-03-12', 'PRESENTE', 129),
('2025-03-13', 'AUSENTE', 129),
('2025-03-14', 'TARDE', 129),

/* ID ESTUDIANTE 130 */
('2025-03-03', 'PRESENTE', 130),
('2025-03-04', 'AUSENTE', 130),
('2025-03-05', 'PRESENTE', 130),
('2025-03-06', 'PRESENTE', 130),
('2025-03-07', 'PRESENTE', 130),
('2025-03-10', 'TARDE', 130),
('2025-03-11', 'PRESENTE', 130),
('2025-03-12', 'PRESENTE', 130),
('2025-03-13', 'TARDE', 130),
('2025-03-14', 'PRESENTE', 130),

/* ID ESTUDIANTE 131 */
('2025-03-03', 'AUSENTE', 131),
('2025-03-04', 'PRESENTE', 131),
('2025-03-05', 'PRESENTE', 131),
('2025-03-06', 'PRESENTE', 131),
('2025-03-07', 'TARDE', 131),
('2025-03-10', 'PRESENTE', 131),
('2025-03-11', 'PRESENTE', 131),
('2025-03-12', 'PRESENTE', 131),
('2025-03-13', 'TARDE', 131),
('2025-03-14', 'PRESENTE', 131),

/* ID ESTUDIANTE 132 */
('2025-03-03', 'PRESENTE', 132),
('2025-03-04', 'TARDE', 132),
('2025-03-05', 'PRESENTE', 132),
('2025-03-06', 'PRESENTE', 132),
('2025-03-07', 'PRESENTE', 132),
('2025-03-10', 'PRESENTE', 132),
('2025-03-11', 'TARDE', 132),
('2025-03-12', 'PRESENTE', 132),
('2025-03-13', 'PRESENTE', 132),
('2025-03-14', 'AUSENTE', 132);