-- Script was generated by Devart dbForge Studio for MySQL, Version 6.0.128.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 26/11/2025 12:17:01
-- Server version: 5.5.5-10.4.32-MariaDB
-- Client version: 4.1

SET NAMES 'utf8';
USE `tif_escuela`;
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(1, True, 'Matías Ruiz', 'PRIMERO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(2, True, 'Vanesa Leiva', 'SEGUNDO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(3, True, 'Julieta Pérez', 'TERCERO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(4, True, 'Adriana Arias', 'CUARTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(5, True, 'Pedro González', 'QUINTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(6, True, 'Daiana Giménez', 'SEXTO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(7, True, 'Roxana Costa', 'SEPTIMO', 'MAÑANA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(8, True, 'Juan Pérez', 'PRIMERO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(9, True, 'María Fernández', 'SEGUNDO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(10, True, 'Laura González', 'TERCERO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(11, True, 'Sofía Gómez', 'CUARTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(12, True, 'Esteban Sánchez', 'QUINTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(13, True, 'Ana Ruiz', 'SEXTO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(14, True, 'Diego Díaz', 'SEPTIMO', 'TARDE');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(15, True, 'Andrés Benítez', 'PRIMERO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(16, True, 'Marcela Morales', 'SEGUNDO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(17, True, 'Sofía Mariana Gómez', 'TERCERO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(18, True, 'Alejandro López', 'CUARTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(19, True, 'Valeria Torres', 'QUINTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(20, True, 'Gabriela Acosta', 'SEXTO', 'JORNADA_COMPLETA');
INSERT INTO tif_escuela.grados(id_grado, activo, docente, nombre, turno) VALUES
(21, True, 'Florencia Benítez', 'SEPTIMO', 'JORNADA_COMPLETA');
